workspace:
  base: /go
  path: src/github.com/walmav/microservice

pipeline:
  deps:
   image: golang:latest
   commands:
      - go get
      - go test
  build:
    image: node:latest
    commands:
      - go build
