workspace:
  base: /go
  path: src/github.com/walmav/microservice
pipeline:
   build:
     image: golang:latest
     commands:
       - go get
       - go build
       - echo $DOCKER_USERNAME
       - echo $DOCKER_PASSWORD	
   publish:
      image: plugins/docker
      repo: mavwali/poc
      secrets: [ docker_username, docker_password ]
