workspace:
  base: /go
  path: src/github.com/walmav/microservice
pipeline:
   build:
     image: golang:latest
     commands:
       - go get
       - go build
   publish:
      image: plugins/docker
      repo: mavwali/poc
