workspace:
   base: /go
   path: src/github.com/walmav/microservice
pipeline:
   build:
     image: golang:latest
     commands:
       - cd skeleton
       - go get
       - go build
   docker:
      context: /go/src/github.com/walmav/microservice/skeleton
      dockerfile: /go/src/github.com/walmav/microservice/skeleton/Dockerfile
      image: plugins/docker
      repo: mavwali/poc
      secrets: [ docker_username, docker_password ]

   build:
     image: golang:latest
     commands:
       - cd register
       - go get
       - go build
   docker:
      context: /go/src/github.com/walmav/microservice/register
      dockerfile: /go/src/github.com/walmav/microservice/register/Dockerfile
      image: plugins/docker
      repo: mavwali/poc
      secrets: [ docker_username, docker_password ]
